version: '3.6'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../:/var/www
    links:
      - php
    depends_on:
      - php

  php:
    volumes:
       - ../../:/var/www
    image: php:7.3-fpm

#  mariadb:
#      image: mariadb:10.4
#      ports:
#          - "33306:3306"
#      environment:
#          MYSQL_ROOT_PASSWORD: lopata
#      volumes:
#          - mariadb:/var/lib/mysql


volumes:
    mariadb: {}
